name: Run testes

on: 
  push:
    branches: [main]
    
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Instalar as deps
        uses: bahmutov/npm-install@v1 
        with:
          working-directory: server  
      - name: Instalar as deps da web
        uses: bahmutov/npm-install@v1 
        with:
          working-directory: web
      - name: Component & API & UI Tests
        uses: cypress-io/github-action@v2
        with:
          working-directory: web
          install: false
          start: npm run start:ci
          wait-on: "http://localhost:3000"
          
          
      
# baixar o codigo na maquina 
# instalar as dependencias
# subir as aplicações server / web
# executar os testes
